"""Agent orchestrator (plan / execute) integration tests (need a live database).

These run with the AI layer disabled (no OPENAI_API_KEY in CI), so they exercise
the deterministic heuristic + rule-based recommendation path — the path that
must always work."""
from __future__ import annotations

import uuid

from fastapi.testclient import TestClient

from main import app

client = TestClient(app)

CORE_MODULE_IDS = {
    "microsite_config",
    "damage_report_form",
    "volunteer_form",
    "supply_form",
    "map_bundle",
    "public_notice_draft",
}


def _plan(message: str, incident_id: str | None = None) -> dict:
    body = {"message": message}
    if incident_id:
        body["incident_id"] = incident_id
    resp = client.post("/v1/agent/plan", json=body)
    assert resp.status_code == 200, resp.text
    return resp.json()


def test_plan_detects_earthquake_and_creates_incident():
    plan = _plan("花蓮外海發生規模7.2強烈地震，市區傳出建物倒塌")
    assert plan["incident"]["scenario_type"] == "earthquake"
    assert plan["incident"]["status"] == "draft"
    assert plan["intent_mode"] in {"ai", "heuristic"}

    ids = {p["id"] for p in plan["proposals"]}
    assert CORE_MODULE_IDS.issubset(ids)
    # earthquake-specific recommendation surfaces SOS + shelter map
    reco = {p["id"] for p in plan["proposals"] if p["recommended"]}
    assert "sos_form" in reco
    assert "shelter_map" in reco
    # recommended proposals are sorted to the front
    assert plan["proposals"][0]["recommended"] is True


def test_plan_detects_typhoon():
    plan = _plan("強烈颱風即將登陸，沿海鄉鎮預警淹水")
    # typhoon keyword wins
    assert plan["incident"]["scenario_type"] in {"typhoon", "flood"}


def test_plan_unknown_falls_back_to_generic():
    plan = _plan("某種不明狀況需要協助")
    assert plan["incident"]["scenario_type"] == "generic"
    # generic still offers the core modules
    ids = {p["id"] for p in plan["proposals"]}
    assert CORE_MODULE_IDS.issubset(ids)


def test_plan_proposals_only_include_executable_generators():
    plan = _plan("地震災害")
    types = {p["module_type"] for p in plan["proposals"]}
    assert types == {"generator"}
    ids = {p["id"] for p in plan["proposals"]}
    assert "needs_matching_engine" not in ids  # not implemented => not proposed


def test_plan_then_execute_generates_only_selected():
    plan = _plan("光復鄉堰塞湖溢流")
    iid = plan["incident"]["id"]

    resp = client.post(
        "/v1/agent/execute",
        json={"incident_id": iid, "module_ids": ["microsite_config", "evacuation_guide"]},
    )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["created_count"] == 2
    assert body["failed_count"] == 0
    statuses = {r["module_id"]: r["status"] for r in body["results"]}
    assert statuses == {"microsite_config": "created", "evacuation_guide": "created"}

    arts = client.get("/v1/artifacts", params={"incident_id": iid}).json()
    assert {a["artifact_type"] for a in arts["items"]} == {
        "microsite_config",
        "evacuation_guide",
    }
    # generated by the agent path, still pending_review (review gate intact)
    assert all(a["status"] == "pending_review" for a in arts["items"])


def test_execute_is_idempotent_and_reports_skipped():
    plan = _plan("地震")
    iid = plan["incident"]["id"]
    client.post("/v1/agent/execute", json={"incident_id": iid, "module_ids": ["sos_form"]})

    again = client.post(
        "/v1/agent/execute", json={"incident_id": iid, "module_ids": ["sos_form"]}
    ).json()
    assert again["skipped_count"] == 1
    assert again["created_count"] == 0
    assert again["results"][0]["status"] == "skipped"
    assert again["results"][0]["artifact_id"] is not None


def test_execute_isolates_failures():
    plan = _plan("颱風")
    iid = plan["incident"]["id"]

    body = client.post(
        "/v1/agent/execute",
        json={
            "incident_id": iid,
            "module_ids": ["evacuation_guide", "needs_matching_engine", "fb_page_post"],
        },
    ).json()
    statuses = {r["module_id"]: r["status"] for r in body["results"]}
    assert statuses["evacuation_guide"] == "created"
    assert statuses["fb_page_post"] == "created"  # not blocked by the failure
    assert statuses["needs_matching_engine"] == "failed"
    assert body["created_count"] == 2
    assert body["failed_count"] == 1


def test_plan_with_existing_incident_does_not_duplicate():
    plan1 = _plan("堰塞湖災害")
    iid = plan1["incident"]["id"]
    plan2 = _plan("補充資訊", incident_id=iid)
    assert plan2["incident"]["id"] == iid
    assert plan2["intent_mode"] == "existing"

    incidents = client.get("/v1/incidents", params={"limit": 100}).json()["items"]
    assert sum(1 for i in incidents if i["id"] == iid) == 1


def test_execute_missing_incident_404():
    resp = client.post(
        "/v1/agent/execute",
        json={"incident_id": str(uuid.uuid4()), "module_ids": ["sos_form"]},
    )
    assert resp.status_code == 404


def test_plan_outbox_records_agent_planned():
    plan = _plan("地震災害事件 outbox 測試")
    iid = plan["incident"]["id"]
    events = client.get("/v1/events/outbox", params={"limit": 100}).json()["items"]
    types = {
        e["event_type"]
        for e in events
        if e.get("payload", {}).get("incident_id") == iid
    }
    assert "agent.planned" in types
